# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:/masaüstü/yazılımileilgilihersey/onluk/Web scrabbing/vfsglobal randevu sistemi/anasayfa.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(994, 818)
        self.KayitEkle = QtWidgets.QPushButton(Widget)
        self.KayitEkle.setGeometry(QtCore.QRect(830, 20, 131, 51))
        self.KayitEkle.setObjectName("KayitEkle")
        self.Baslat = QtWidgets.QPushButton(Widget)
        self.Baslat.setGeometry(QtCore.QRect(460, 310, 131, 51))
        self.Baslat.setObjectName("Baslat")
        self.line = QtWidgets.QFrame(Widget)
        self.line.setGeometry(QtCore.QRect(-10, 70, 1001, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.kupon_id_label_5 = QtWidgets.QLabel(Widget)
        self.kupon_id_label_5.setGeometry(QtCore.QRect(50, 20, 551, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        self.kupon_id_label_5.setFont(font)
        self.kupon_id_label_5.setObjectName("kupon_id_label_5")
        self.line_3 = QtWidgets.QFrame(Widget)
        self.line_3.setGeometry(QtCore.QRect(0, 0, 991, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.giris_label1 = QtWidgets.QLabel(Widget)
        self.giris_label1.setGeometry(QtCore.QRect(640, 70, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.giris_label1.setFont(font)
        self.giris_label1.setObjectName("giris_label1")
        self.giris1 = QtWidgets.QLineEdit(Widget)
        self.giris1.setGeometry(QtCore.QRect(770, 80, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.giris1.setFont(font)
        self.giris1.setText("")
        self.giris1.setObjectName("giris1")
        self.kupon_id_label_11 = QtWidgets.QLabel(Widget)
        self.kupon_id_label_11.setGeometry(QtCore.QRect(20, 180, 201, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.kupon_id_label_11.setFont(font)
        self.kupon_id_label_11.setObjectName("kupon_id_label_11")
        self.Kayitlar_list = QtWidgets.QListWidget(Widget)
        self.Kayitlar_list.setGeometry(QtCore.QRect(20, 230, 201, 161))
        self.Kayitlar_list.setObjectName("Kayitlar_list")
        self.line_4 = QtWidgets.QFrame(Widget)
        self.line_4.setGeometry(QtCore.QRect(0, 180, 621, 16))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_6 = QtWidgets.QFrame(Widget)
        self.line_6.setGeometry(QtCore.QRect(-10, 660, 1001, 16))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.Bolge = QtWidgets.QComboBox(Widget)
        self.Bolge.setGeometry(QtCore.QRect(10, 130, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.Bolge.setFont(font)
        self.Bolge.setObjectName("Bolge")
        self.Bolge.addItem("")
        self.Bolge.addItem("")
        self.Bolge.addItem("")
        self.Bolge.addItem("")
        self.Bolge.addItem("")
        self.Bolge.addItem("")
        self.Bolge.addItem("")
        self.Bolge.addItem("")
        self.Kategori = QtWidgets.QComboBox(Widget)
        self.Kategori.setGeometry(QtCore.QRect(210, 130, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.Kategori.setFont(font)
        self.Kategori.setObjectName("Kategori")
        self.Kategori.addItem("")
        self.Kategori.addItem("")
        self.kupon_id_label_12 = QtWidgets.QLabel(Widget)
        self.kupon_id_label_12.setGeometry(QtCore.QRect(10, 70, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.kupon_id_label_12.setFont(font)
        self.kupon_id_label_12.setObjectName("kupon_id_label_12")
        self.AltKategori = QtWidgets.QComboBox(Widget)
        self.AltKategori.setGeometry(QtCore.QRect(410, 130, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.AltKategori.setFont(font)
        self.AltKategori.setObjectName("AltKategori")
        self.AltKategori.addItem("")
        self.AltKategori.addItem("")
        self.AltKategori.addItem("")
        self.kupon_id_label_13 = QtWidgets.QLabel(Widget)
        self.kupon_id_label_13.setGeometry(QtCore.QRect(210, 70, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.kupon_id_label_13.setFont(font)
        self.kupon_id_label_13.setObjectName("kupon_id_label_13")
        self.kupon_id_label_14 = QtWidgets.QLabel(Widget)
        self.kupon_id_label_14.setGeometry(QtCore.QRect(410, 70, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.kupon_id_label_14.setFont(font)
        self.kupon_id_label_14.setObjectName("kupon_id_label_14")
        self.line_2 = QtWidgets.QFrame(Widget)
        self.line_2.setGeometry(QtCore.QRect(610, 10, 20, 661))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.giris2 = QtWidgets.QLineEdit(Widget)
        self.giris2.setGeometry(QtCore.QRect(770, 130, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.giris2.setFont(font)
        self.giris2.setText("")
        self.giris2.setObjectName("giris2")
        self.giris_label2 = QtWidgets.QLabel(Widget)
        self.giris_label2.setGeometry(QtCore.QRect(640, 120, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.giris_label2.setFont(font)
        self.giris_label2.setObjectName("giris_label2")
        self.giris3 = QtWidgets.QLineEdit(Widget)
        self.giris3.setGeometry(QtCore.QRect(770, 180, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.giris3.setFont(font)
        self.giris3.setText("")
        self.giris3.setObjectName("giris3")
        self.giris_label3 = QtWidgets.QLabel(Widget)
        self.giris_label3.setGeometry(QtCore.QRect(640, 170, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.giris_label3.setFont(font)
        self.giris_label3.setObjectName("giris_label3")
        self.giris4 = QtWidgets.QLineEdit(Widget)
        self.giris4.setGeometry(QtCore.QRect(770, 230, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.giris4.setFont(font)
        self.giris4.setText("")
        self.giris4.setObjectName("giris4")
        self.giris_label4 = QtWidgets.QLabel(Widget)
        self.giris_label4.setGeometry(QtCore.QRect(640, 220, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.giris_label4.setFont(font)
        self.giris_label4.setObjectName("giris_label4")
        self.giris_label7 = QtWidgets.QLabel(Widget)
        self.giris_label7.setGeometry(QtCore.QRect(640, 370, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.giris_label7.setFont(font)
        self.giris_label7.setObjectName("giris_label7")
        self.giris7 = QtWidgets.QLineEdit(Widget)
        self.giris7.setGeometry(QtCore.QRect(770, 380, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.giris7.setFont(font)
        self.giris7.setText("")
        self.giris7.setObjectName("giris7")
        self.giris5 = QtWidgets.QLineEdit(Widget)
        self.giris5.setGeometry(QtCore.QRect(770, 280, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.giris5.setFont(font)
        self.giris5.setText("")
        self.giris5.setObjectName("giris5")
        self.giris_label5 = QtWidgets.QLabel(Widget)
        self.giris_label5.setGeometry(QtCore.QRect(640, 270, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.giris_label5.setFont(font)
        self.giris_label5.setObjectName("giris_label5")
        self.giris8 = QtWidgets.QLineEdit(Widget)
        self.giris8.setGeometry(QtCore.QRect(770, 430, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.giris8.setFont(font)
        self.giris8.setText("")
        self.giris8.setObjectName("giris8")
        self.giris6 = QtWidgets.QLineEdit(Widget)
        self.giris6.setGeometry(QtCore.QRect(770, 330, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.giris6.setFont(font)
        self.giris6.setText("")
        self.giris6.setObjectName("giris6")
        self.giris_label6 = QtWidgets.QLabel(Widget)
        self.giris_label6.setGeometry(QtCore.QRect(640, 320, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.giris_label6.setFont(font)
        self.giris_label6.setObjectName("giris_label6")
        self.giris_label8 = QtWidgets.QLabel(Widget)
        self.giris_label8.setGeometry(QtCore.QRect(640, 420, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.giris_label8.setFont(font)
        self.giris_label8.setObjectName("giris_label8")
        self.giris_label10 = QtWidgets.QLabel(Widget)
        self.giris_label10.setGeometry(QtCore.QRect(640, 520, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.giris_label10.setFont(font)
        self.giris_label10.setObjectName("giris_label10")
        self.giris_label9 = QtWidgets.QLabel(Widget)
        self.giris_label9.setGeometry(QtCore.QRect(640, 470, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.giris_label9.setFont(font)
        self.giris_label9.setObjectName("giris_label9")
        self.giris10 = QtWidgets.QLineEdit(Widget)
        self.giris10.setGeometry(QtCore.QRect(770, 530, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.giris10.setFont(font)
        self.giris10.setText("")
        self.giris10.setObjectName("giris10")
        self.giris9 = QtWidgets.QLineEdit(Widget)
        self.giris9.setGeometry(QtCore.QRect(770, 480, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.giris9.setFont(font)
        self.giris9.setText("")
        self.giris9.setObjectName("giris9")
        self.line_5 = QtWidgets.QFrame(Widget)
        self.line_5.setGeometry(QtCore.QRect(980, 10, 20, 661))
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.kupon_id_label_22 = QtWidgets.QLabel(Widget)
        self.kupon_id_label_22.setGeometry(QtCore.QRect(790, 670, 201, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.kupon_id_label_22.setFont(font)
        self.kupon_id_label_22.setObjectName("kupon_id_label_22")
        self.KrediKartiList = QtWidgets.QListWidget(Widget)
        self.KrediKartiList.setGeometry(QtCore.QRect(230, 230, 201, 161))
        self.KrediKartiList.setObjectName("KrediKartiList")
        self.KrediKartiCheck = QtWidgets.QCheckBox(Widget)
        self.KrediKartiCheck.setGeometry(QtCore.QRect(230, 190, 201, 26))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.KrediKartiCheck.setFont(font)
        self.KrediKartiCheck.setObjectName("KrediKartiCheck")
        self.KrediKartiEkle = QtWidgets.QPushButton(Widget)
        self.KrediKartiEkle.setGeometry(QtCore.QRect(420, 610, 131, 51))
        self.KrediKartiEkle.setObjectName("KrediKartiEkle")
        self.giris_label1_2 = QtWidgets.QLabel(Widget)
        self.giris_label1_2.setGeometry(QtCore.QRect(230, 390, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.giris_label1_2.setFont(font)
        self.giris_label1_2.setObjectName("giris_label1_2")
        self.giris_label1_3 = QtWidgets.QLabel(Widget)
        self.giris_label1_3.setGeometry(QtCore.QRect(640, 20, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.giris_label1_3.setFont(font)
        self.giris_label1_3.setObjectName("giris_label1_3")
        self.giris_label3_2 = QtWidgets.QLabel(Widget)
        self.giris_label3_2.setGeometry(QtCore.QRect(10, 550, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.giris_label3_2.setFont(font)
        self.giris_label3_2.setObjectName("giris_label3_2")
        self.giris_label5_2 = QtWidgets.QLabel(Widget)
        self.giris_label5_2.setGeometry(QtCore.QRect(310, 440, 101, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.giris_label5_2.setFont(font)
        self.giris_label5_2.setObjectName("giris_label5_2")
        self.kartno = QtWidgets.QLineEdit(Widget)
        self.kartno.setGeometry(QtCore.QRect(90, 450, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.kartno.setFont(font)
        self.kartno.setText("")
        self.kartno.setObjectName("kartno")
        self.giris_label7_2 = QtWidgets.QLabel(Widget)
        self.giris_label7_2.setGeometry(QtCore.QRect(310, 540, 221, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.giris_label7_2.setFont(font)
        self.giris_label7_2.setObjectName("giris_label7_2")
        self.kod = QtWidgets.QLineEdit(Widget)
        self.kod.setGeometry(QtCore.QRect(90, 600, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.kod.setFont(font)
        self.kod.setText("")
        self.kod.setObjectName("kod")
        self.giris_label6_2 = QtWidgets.QLabel(Widget)
        self.giris_label6_2.setGeometry(QtCore.QRect(310, 490, 101, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.giris_label6_2.setFont(font)
        self.giris_label6_2.setObjectName("giris_label6_2")
        self.adres = QtWidgets.QLineEdit(Widget)
        self.adres.setGeometry(QtCore.QRect(420, 500, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.adres.setFont(font)
        self.adres.setText("")
        self.adres.setObjectName("adres")
        self.yil = QtWidgets.QLineEdit(Widget)
        self.yil.setGeometry(QtCore.QRect(90, 550, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.yil.setFont(font)
        self.yil.setText("")
        self.yil.setObjectName("yil")
        self.adisoyadi = QtWidgets.QLineEdit(Widget)
        self.adisoyadi.setGeometry(QtCore.QRect(420, 450, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.adisoyadi.setFont(font)
        self.adisoyadi.setText("")
        self.adisoyadi.setObjectName("adisoyadi")
        self.postakodu = QtWidgets.QLineEdit(Widget)
        self.postakodu.setGeometry(QtCore.QRect(420, 550, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.postakodu.setFont(font)
        self.postakodu.setText("")
        self.postakodu.setObjectName("postakodu")
        self.giris_label1_4 = QtWidgets.QLabel(Widget)
        self.giris_label1_4.setGeometry(QtCore.QRect(10, 450, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.giris_label1_4.setFont(font)
        self.giris_label1_4.setObjectName("giris_label1_4")
        self.giris_label4_2 = QtWidgets.QLabel(Widget)
        self.giris_label4_2.setGeometry(QtCore.QRect(10, 600, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.giris_label4_2.setFont(font)
        self.giris_label4_2.setObjectName("giris_label4_2")
        self.ay = QtWidgets.QLineEdit(Widget)
        self.ay.setGeometry(QtCore.QRect(90, 500, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.ay.setFont(font)
        self.ay.setText("")
        self.ay.setObjectName("ay")
        self.giris_label2_2 = QtWidgets.QLabel(Widget)
        self.giris_label2_2.setGeometry(QtCore.QRect(10, 500, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.giris_label2_2.setFont(font)
        self.giris_label2_2.setObjectName("giris_label2_2")
        self.kupon_id_label_23 = QtWidgets.QLabel(Widget)
        self.kupon_id_label_23.setGeometry(QtCore.QRect(10, 670, 301, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.kupon_id_label_23.setFont(font)
        self.kupon_id_label_23.setObjectName("kupon_id_label_23")
        self.HataKodu = QtWidgets.QLabel(Widget)
        self.HataKodu.setGeometry(QtCore.QRect(150, 680, 631, 101))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.HataKodu.setFont(font)
        self.HataKodu.setText("")
        self.HataKodu.setObjectName("HataKodu")
        self.vfssifre = QtWidgets.QLineEdit(Widget)
        self.vfssifre.setGeometry(QtCore.QRect(770, 630, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.vfssifre.setFont(font)
        self.vfssifre.setText("")
        self.vfssifre.setObjectName("vfssifre")
        self.giris_label10_2 = QtWidgets.QLabel(Widget)
        self.giris_label10_2.setGeometry(QtCore.QRect(640, 620, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.giris_label10_2.setFont(font)
        self.giris_label10_2.setObjectName("giris_label10_2")
        self.vfsmail = QtWidgets.QLineEdit(Widget)
        self.vfsmail.setGeometry(QtCore.QRect(770, 580, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.vfsmail.setFont(font)
        self.vfsmail.setText("")
        self.vfsmail.setObjectName("vfsmail")
        self.giris_label9_2 = QtWidgets.QLabel(Widget)
        self.giris_label9_2.setGeometry(QtCore.QRect(640, 570, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.giris_label9_2.setFont(font)
        self.giris_label9_2.setObjectName("giris_label9_2")
        self.yenile = QtWidgets.QPushButton(Widget)
        self.yenile.setGeometry(QtCore.QRect(460, 240, 131, 51))
        self.yenile.setObjectName("yenile")
        self.line_8 = QtWidgets.QFrame(Widget)
        self.line_8.setGeometry(QtCore.QRect(0, 430, 621, 16))
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.line_9 = QtWidgets.QFrame(Widget)
        self.line_9.setGeometry(QtCore.QRect(0, 390, 621, 16))
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")

        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Widget"))
        self.KayitEkle.setText(_translate("Widget", "Ekle"))
        self.Baslat.setText(_translate("Widget", "BAŞLAT"))
        self.kupon_id_label_5.setText(_translate("Widget", "VFS GLOBAL RANDEVU SİSTEMİ V 1.0.0"))
        self.giris_label1.setText(_translate("Widget", "İsim :"))
        self.kupon_id_label_11.setText(_translate("Widget", "Bulunan kayıtlar"))
        self.Bolge.setItemText(0, _translate("Widget", "Beyaz Bölge"))
        self.Bolge.setItemText(1, _translate("Widget", "Kırmızı Bölge"))
        self.Bolge.setItemText(2, _translate("Widget", "ANKARA"))
        self.Bolge.setItemText(3, _translate("Widget", "ANTALYA"))
        self.Bolge.setItemText(4, _translate("Widget", "BEYOGLU"))
        self.Bolge.setItemText(5, _translate("Widget", "GAZIANTEP"))
        self.Bolge.setItemText(6, _translate("Widget", "IZMIR"))
        self.Bolge.setItemText(7, _translate("Widget", "TRABZON"))
        self.Kategori.setItemText(0, _translate("Widget", "Uzun Dönem"))
        self.Kategori.setItemText(1, _translate("Widget", "Kısa Dönem"))
        self.kupon_id_label_12.setText(_translate("Widget", "Bölge Seçimi"))
        self.AltKategori.setItemText(0, _translate("Widget", "Yuksek Öğrenim"))
        self.AltKategori.setItemText(1, _translate("Widget", "Çalışma İzni"))
        self.AltKategori.setItemText(2, _translate("Widget", "Diğer Uzun Dönem"))
        self.kupon_id_label_13.setText(_translate("Widget", "Kategori Seçimi"))
        self.kupon_id_label_14.setText(_translate("Widget", "Alt Kategori Seçimi"))
        self.giris_label2.setText(_translate("Widget", "Soyad :"))
        self.giris_label3.setText(_translate("Widget", "Cinsiyet :"))
        self.giris_label4.setText(_translate("Widget", "Doğum tariği :"))
        self.giris_label7.setText(_translate("Widget", "Pasaport Tarih :"))
        self.giris_label5.setText(_translate("Widget", "Uyruk :"))
        self.giris_label6.setText(_translate("Widget", "Pasaport No :"))
        self.giris_label8.setText(_translate("Widget", "Tel alan kodu :"))
        self.giris_label10.setText(_translate("Widget", "E-Mail :"))
        self.giris_label9.setText(_translate("Widget", "Telefon No :"))
        self.kupon_id_label_22.setText(_translate("Widget", "batuhanokmen.com"))
        self.KrediKartiCheck.setText(_translate("Widget", "Kredi Kartı Bilgisi"))
        self.KrediKartiEkle.setText(_translate("Widget", "Ekle"))
        self.giris_label1_2.setText(_translate("Widget", "Kredi Kartı Ekle"))
        self.giris_label1_3.setText(_translate("Widget", "Yeni Kayıt Ekle"))
        self.giris_label3_2.setText(_translate("Widget", "Yıl :"))
        self.giris_label5_2.setText(_translate("Widget", "Adı Soyadı :"))
        self.giris_label7_2.setText(_translate("Widget", "Postakodu :"))
        self.giris_label6_2.setText(_translate("Widget", "Adres :"))
        self.giris_label1_4.setText(_translate("Widget", "Kart No :"))
        self.giris_label4_2.setText(_translate("Widget", "Kod:"))
        self.giris_label2_2.setText(_translate("Widget", "AY :"))
        self.kupon_id_label_23.setText(_translate("Widget", "Hata Kodu : "))
        self.giris_label10_2.setText(_translate("Widget", "VFS SIFRE :"))
        self.giris_label9_2.setText(_translate("Widget", "VFS MAİL :"))
        self.yenile.setText(_translate("Widget", "Yenile"))

